X_RES = 320
Y_RES = 240
UPTIME_UPDATE_INTERVAL = 1
TEMP_UPDATE_INTERVAL= 30
DEBUG_MODE_DEFAULT = False
THREADS_DEFAULT = 3
DECIMATE_DEFAULT = 1.0
BLUR_DEFAULT = 0.0
REFINE_EDGES_DEFAULT = True
SHARPENING_DEFAULT = 0.25
APRILTAG_DEBUG_MODE_DEFAULT = False
DECISION_MARGIN_DEFAULT = 125
CAMERA_CAL_FILE_NAME = "MultiMatrix.npz.PiGS.640.480" # "MultiMatrix.npz" #"MultiMatrix.npz.PiGS.320.240" #"MultiMatrix.npz" #MultiMatrix.npz.PiGS.640.480" # "MultiMatrix.npz.PiGS.320.240" # "MultiMatrix.npz.webcam.320.240" # "MultiMatrix.npz.webcam.640.480"
THREADS_TOPIC_NAME = "/Vision/Threads"
DECIMATE_TOPIC_NAME = "/Vision/Decimate"
BLUR_TOPIC_NAME = "/Vision/Blur"
REFINE_EDGES_TOPIC_NAME = "/Vision/Edge Refine"
SHARPENING_TOPIC_NAME = "/Vision/Sharpening"
APRILTAG_DEBUG_MODE_TOPIC_NAME = "/Vision/April Tag Debug"
DECISION_MARGIN_MIN_TOPIC_NAME = "/Vision/Decision Margin Min"
DECISION_MARGIN_MAX_TOPIC_NAME = "/Vision/Decision Margin Max"
TAG_CONFIG_FILE_TOPIC_NAME = "/Vision/Tag Config File"
#ACTIVE_TOPIC_NAME = "/Vision/Active"
TAG_ACTIVE_TOPIC_NAME = "/Vision/Tag Active" 
FUEL_ACTIVE_TOPIC_NAME = "/Vision/Fuel Active" 
POSE_DATA_RAW_TOPIC_NAME = "Tag Pose Data Bytes" #cannot say /Vision becuase we already do in NTGetRaw
FUEL_POSE_DATA_RAW_TOPIC_NAME = "Fuel Pose Data Bytes" #cannot say /Vision becuase we already do in NTGetRaw
POSE_DATA_STRING_TOPIC_NAME_HEADER ="/Vision/Pose Data Header"
FUEL_POSE_DATA_STRING_TOPIC_NAME_HEADER = "/Vision/Fuel Pose Data Header"
POSE_DATA_STRING_TOPIC_NAME_DATA_TRANSLATION ="/Vision/Pose Data Trans"
POSE_DATA_STRING_TOPIC_NAME_DATA_ROTATION ="/Vision/Pose Data Rot"
TAG_PI_TEMP_TOPIC_NAME = "/Vision/Tag Temperature"
FUEL_PI_TEMP_TOPIC_NAME = "/Vision/Fuel Temperature"
RIO_TIME_TOPIC_NAME = "/Vision/RIO Time"

Z_IN_TOPIC_NAME = "/Vision/Z In"
FUEL_MIN_HUE_TOPIC_NAME = "/Vision/Fuel Min Hue"
FUEL_MIN_SAT_TOPIC_NAME = "/Vision/Fuel Min Sat"
FUEL_MIN_VAL_TOPIC_NAME = "/Vision/Fuel Min Val"
FUEL_MAX_HUE_TOPIC_NAME = "/Vision/Fuel Max Hue"
FUEL_MAX_SAT_TOPIC_NAME = "/Vision/Fuel Max Sat"
FUEL_MAX_VAL_TOPIC_NAME = "/Vision/Fuel Max Val"
FUEL_CONFIG_FILE_TOPIC_NAME = "/Vision/Fuel Config File"
FUEL_CONFIG_FILE_DEFAULT = "fuel_config.ini"
TAG_CONFIG_FILE_DEFAULT = "tag_config.ini"
GEN_CONFIG_FILE_DEFAULT = "gen_config.ini"
FUEL_MIN_HUE = 0
FUEL_MIN_SAT = 0
FUEL_MIN_VAL = 0
FUEL_MAX_HUE = 179
FUEL_MAX_SAT = 255
FUEL_MAX_VAL = 255
TAG_ENABLE_TOPIC_NAME = "/Vision/Tag Enable"
FUEL_ENABLE_TOPIC_NAME = "/Vision/Fuel Enable"
TOP_LINE_DIST_FROM_TOP = 0.15
BOTTOM_LINE_DIST_FROM_TOP = 0.7
FUEL_MIN_AREA_TOPIC_NAME = "/Vision/Fuel Min Area"
FUEL_MIN_AREA = 44 #275
FUEL_ANGLE_TOPIC_NAME = "/Vision/Fuel Angle"
WRITE_TAG_IMAGE = False
TAG_RECORD_ENABLE_TOPIC_NAME = "/Vision/Tag Record"
TAG_RECORD_REMOVE_TOPIC_NAME = "/Vision/Tag Remove"
FUEL_RECORD_DATA_TOPIC_NAME = "/Vision/Fuel Record"
FUEL_X_OFFSET = 0
FUEL_Y_OFFSET = 5
FPS_NUM_SAMPLES = 100 #after this number of images the fps average is calulated
TAG_CROP_TOP_TOPIC_NAME = "/Vision/Tag Crop Top"
TAG_CROP_BOTTOM_TOPIC_NAME = "/Vision/Tag Crop Bottom"
TAG_CROP_TOP_DEFAULT = 0 # this is a %; default to no crop
TAG_CROP_BOTTOM_DEFAULT = 100 # this is a %; default to no crop
FUEL_NUM_PIXELS_FROM_CENTER_BLANK = 15
TAG_BRIGHTNESS_TOPIC_NAME = "/Vision/Tag Brightness"
FUEL_BRIGHTNESS_TOPIC_NAME = "/Vision/Fuel Brightness"

BRIGHTNESS_DEFAULT = 0.0
TAG_CONTRAST_TOPIC_NAME = "/Vision/Tag Contrast"
FUEL_CONTRAST_TOPIC_NAME = "/Vision/Fuel Contrast"
CONTRAST_DEFAULT = 1.0

FUEL_AMOUNT_DETECT_MODE_TOPIC_NAME = "/Vision/Fuel Amount Detection Mode"
FUEL_AMOUNT_DETECT_MODE_DEFAULT = 2

GEN_FUEL_Y_OFFSET_TOPIC_NAME = "/Vision/Fuel Y Offset"

TAG_ERRORS_TOPIC_NAME = "/Vision/Tag Corrected Errors"
TAG_ERRORS_DEFAULT = 0
TAG_AE_TOPIC_NAME = "/Vision/Tag Auto Exposure"
FUEL_AE_TOPIC_NAME = "/Vision/Fuel Auto Exposure"
AE_DEFAULT = True
TAG_EXPOSURE_TOPIC_NAME = "/Vision/Tag Manual Exposure" # only used if AE_TOPIC_NAME is disabled
FUEL_EXPOSURE_TOPIC_NAME = "/Vision/Fuel Manual Exposure" # only used if AE_TOPIC_NAME is disabled
EXPOSURE_DEFAULT = 1000 # in microseconds - total guess as default 
POSE_DATA_X_DEG_TOPIC_NAME = "/Vision/X Deg"
POSE_DATA_Y_DEG_TOPIC_NAME = "/Vision/Y Deg"
POSE_DATA_Z_DEG_TOPIC_NAME = "/Vision/Z Deg"
POSE_DATA_X_IN_TOPIC_NAME = "/Vision/X In"
POSE_DATA_Y_IN_TOPIC_NAME = "/Vision/Y In"
TAG_DETECTED_ID_TOPIC_NAME = "/Vision/Tag Id"
TAG_DETECTED_DM_TOPIC_NAME = "/Vision/Tag DM"
TAG_DETECTED_ERRORS_TOPIC_NAME = "/Vision/Tag Errors"
